version: '3.3'

services:

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data